/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Default": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "InvokeMultiSteps": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MOMOS_ApiGatewayV1": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
    "MyPublicBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MyStateMachine": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "UploadSomething": {
      "name": string
      "type": "sst.aws.Function"
    }
    "V1": {
      "type": "sst.aws.Vpc"
    }
    "VPC": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}