---
title: build
displayMode: compact
config:
    theme: forest
    look: handDrawn
    layout: elk
    elk:
        nodePlacementStrategy: SIMPLE
---
    
graph TD
	QHZT("sst-analyzer#build") --> ETTT("___ROOT___")
	JEGP("sst-vsc-ext#build") --> QHZT("sst-analyzer#build")
