name: Release Analyzer Package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/analyzer/**'
      - '.github/workflows/release-analyzer.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - name: Check for changes
        id: changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -E '^packages/analyzer/(src/|package\.json)'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  release:
    needs: check-changes
    if: needs.check-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.13.1'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Code quality check
        run: pnpm run lint --filter=@cute-me-on-repos/sst-analyzer
        
      - name: Build package
        run: pnpm run build --filter=@cute-me-on-repos/sst-analyzer
        
      - name: Get current version
        id: current-version
        run: |
          cd packages/analyzer
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          
      - name: Bump version
        id: bump-version
        run: |
          cd packages/analyzer
          npm version patch --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add packages/analyzer/package.json
          git commit -m "chore(analyzer): bump version to ${{ steps.bump-version.outputs.new-version }}"
          git push
          
      - name: Create and push tag
        run: |
          git tag "analyzer-v${{ steps.bump-version.outputs.new-version }}"
          git push origin "analyzer-v${{ steps.bump-version.outputs.new-version }}"
