name: Testing for Analyzer Package and vscode Extension

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.13.1'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint

  build-and-test-analyzer:
    name: Build, and Test analyzer package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.13.1'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm exec turbo build --filter=@cute-me-on-repos/sst-analyzer
      - name: Test analyzer package
        run: pnpm exec turbo test --filter=@cute-me-on-repos/sst-analyzer
 
  build-and-test-extension:
    name: Build, and Test vscode extension
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.13.1'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm run build
      - name: Test vscode extension (Linux)
        run: cd apps/extension && xvfb-run -a pnpm run test
        if: runner.os == 'Linux'
      - name: Test vscode extension (MacOS, Windows)
        run: pnpm run test --filter=sst-vsc-ext
        if: runner.os != 'Linux'
      - name: Validate extension package (Ubuntu only)
        run: |
          cd apps/extension
          pnpm run package
          echo "✅ Extension package validation passed"
        if: runner.os == 'Linux'
  
